### ISSUE TITLE
Apache 2.0 / MIT

### ISSUE THREAD

**Issue by sirinath** [almondtools/stringsearchalgorithms#11]
Can this be licensed using a permissive licence.

**Comment by almondtools** [comment]
The license is LGPL, which is indeed not as permissive as MIT or Apache 2.0. It requires you to give your customer access (LGPL) to the source code if you modify the library. Which restriction of the LGPL is a problem in your usage scenario?

**Comment by sirinath** [comment]
I don't want to use the whole library. I just want to copy and adopt one algorithm in this case.

But also *GPL is in most organisations restricted licenses. So even if the library is just a dependency there are some who cannot use it.

**Comment by almondtools** [comment]
The license does not inhibit you copying and improving the source code. It just requires you to relicense this part under the same conditions as you licenced it.

Of course I would prefer to know of these improvements such that I can adopt them too, but this is up to you.

I think the LGPL is a fair compromise between the strict GPL and a permissive license, and I am sorry if your organization thinks this compromise is not fair enough.

**Comment by almondtools** [comment]
If there are more questions on licensing - reopen this issue.
