### ISSUE TITLE
Performance heuristics?

### ISSUE THREAD

**Issue by hrstoyanov** [almondtools/stringsearchalgorithms#13]
Thank you for creating this library!

I came across a similar library:
https://github.com/neo-search/multiple-string-searcher

That claims to have introduced performance heuristics over the classic  Aho-Curasik algorithms that make 2x-3x faster. What do you think, is your library able to match it?

Thanks

**Comment by almondtools** [comment]
Thank you for the hint to this library, which I actually did not know from.

The Aho-Corasick variant of stringsearchalgorithms is not the fastest among the implementations known to me. There is at least one library that is faster.

You can see an overview at [stringbench](https://almondtools.github.io/stringbench/chart.html#latest). for "128 strings in strings" you will see that aho corasick of HanKCS is faster (study the benchmark files to get the factor).

I will check the upper library on correctness and performance.

**Comment by almondtools** [comment]
I added [multiple-string-searcher](https://github.com/neo-search/multiple-string-searcher) to [stringbench](https://github.com/almondtools/stringbench) with following results:
- the documentation is wrong in describing how to enable Aho-Corasick-Fast (`StringSearcherBuilder` is hard-coded only to work with standard Aho-Corasick)
- the standard Aho-Corasick is low performing for corner cases (like the algorithm of Aho-Corasick.org), as an example the test for alphabet size 2, pattern size 2 and pattern number 2 does not terminate after 40 seconds. An [issue on Aho-Corasick.org was filed](https://github.com/robert-bor/aho-corasick/issues/36) but ignored.

To keep the test suite of stringbench lean, the incubation test at this time does contain only one example failing test. Look in the history of the Test file if you are interested in performing the whole test.

Maybe I can get Aho-Corasick-Fast to run without the documentation.

**Comment by almondtools** [comment]
Please reopen this issue if the reason is not clear.
