### ISSUE TITLE
Invalid LONGEST_MATCH results from SetBackwardOracleMatching

### ISSUE THREAD

**Issue by sebastianarnold** [almondtools/stringsearchalgorithms#9]
I am using SetBackwardOracleMatching with MatchOption.LONGEST_MATCH to match multiple patterns on a StringCharProvider.

For example: "Die Krankheit ist seit dem Aufkommen wirksamer Antibiotika selten geworden".

- When searching for patterns ("Antibiotik", "Antibiotika"), this configuration returns "Antibiotik", which is not the longest match that I expected. 
- AhoCorasick and WuManber return correct results, but they are too slow or memory-intensive for my applications.
- When I reverse the pattern order, the result is correct – so maybe a solution requires some sort of longest-first sorting?

Please see the unit test provided at https://github.com/almondtools/stringsearchalgorithms/pull/8

**Comment by almondtools** [comment]
Thanks for pointing me to the reverse order solution. The problem should be fixed with the release 0.4.3. Just reopen this issue if the problem keeps persisting.
